SELECT 
    MND.EFFECTIVEDATE,
    CASE 
        WHEN MND.EXTERNALREFERENCE LIKE '%NSW Region%' OR 
             MND.EXTERNALREFERENCE LIKE '%NSW1%' OR 
             MND.EXTERNALREFERENCE LIKE '%New South Wales%' THEN 'NSW'
        WHEN MND.EXTERNALREFERENCE LIKE '%QLD Region%' OR 
             MND.EXTERNALREFERENCE LIKE '%QLD1%' OR 
             MND.EXTERNALREFERENCE LIKE '%Queensland%' THEN 'QLD'
        WHEN MND.EXTERNALREFERENCE LIKE '%SA Region%' OR 
             MND.EXTERNALREFERENCE LIKE '%SA1%' OR 
             MND.EXTERNALREFERENCE LIKE '%South Australia%' THEN 'SA'
        WHEN MND.EXTERNALREFERENCE LIKE '%VIC Region%' OR 
             MND.EXTERNALREFERENCE LIKE '%VIC1%' OR 
             MND.EXTERNALREFERENCE LIKE '%Victoria%' THEN 'VIC'
        WHEN MND.EXTERNALREFERENCE LIKE '%TAS Region%' OR 
             MND.EXTERNALREFERENCE LIKE '%TAS1%' OR 
             MND.EXTERNALREFERENCE LIKE '%Tasmania%' THEN 'TAS'
        ELSE NULL 
    END AS MARKET,
    CASE 
        WHEN MND.EXTERNALREFERENCE LIKE '%LRC%' OR 
             MND.EXTERNALREFERENCE LIKE '%low reserve condition%' THEN 'LRC'
        WHEN MND.EXTERNALREFERENCE LIKE '%LOR1%' OR 
             MND.EXTERNALREFERENCE LIKE '%LOR 1%' THEN 'LOR1'
        WHEN MND.EXTERNALREFERENCE LIKE '%LOR2%' OR
             MND.EXTERNALREFERENCE LIKE '%LOR 2%' THEN 'LOR2'
        WHEN MND.EXTERNALREFERENCE LIKE '%LOR3%' OR
             MND.EXTERNALREFERENCE LIKE '%LOR 3%' THEN 'LOR3'
        ELSE NULL 
    END AS LORTYPE,
    MND.EXTERNALREFERENCE
FROM MARKETNOTICEDATA MND
JOIN MARKETNOTICETYPE MNT ON MND.TYPEID = MNT.TYPEID
WHERE MNT.DESCRIPTION = 'LRC/LOR1/LOR2/LOR3' -- Filter for specific DESCRIPTION
AND LOWER(MND.EXTERNALREFERENCE) LIKE 'actual%'
AND LOWER(MND.EXTERNALREFERENCE) NOT LIKE '%cancellation%'
AND MND.EXTERNALREFERENCE NOT LIKE '%correction%';